<?php
require_once('../vendor/tcpdf/tcpdf.php');
include '../config/db.php';

// Extend TCPDF to create custom Header and Footer
class MYPDF extends TCPDF {
    public function Header() {
        // Logo
        $imageFile = K_PATH_IMAGES . 'logo.png'; // logo in tcpdf/images/logo.png
        if (file_exists($imageFile)) {
            $this->Image($imageFile, 10, 10, 25);
        }

        // Title
        $this->SetFont('helvetica', 'B', 16);
        $this->Cell(0, 15, 'Inventory Report', 0, false, 'C', 0, '', 0, false, 'M', 'M');
    }

    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->Cell(0, 10, 'Generated by Little Public School Inventory System', 0, false, 'C');
    }
}

// Create new PDF
$pdf = new MYPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document info
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Inventory System');
$pdf->SetTitle('Inventory Report');

// Set default header and footer fonts
$pdf->setHeaderFont(['helvetica', '', 12]);
$pdf->setFooterFont(['helvetica', '', 8]);

// Set margins
$pdf->SetMargins(10, 25, 10);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(10);

// Auto page break
$pdf->SetAutoPageBreak(TRUE, 15);

// Font
$pdf->SetFont('dejavusans', '', 10);

// Add page
$pdf->AddPage();

// Fetch inventory
$result = $conn->query("SELECT id, item_name, quantity, description FROM inventory ORDER BY id DESC");

// HTML Table
$html = '
<style>
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #444; padding: 6px; }
    th { background-color: #f2f2f2; }
</style>
<h3 style="margin-bottom:10px;">Inventory Items</h3>
<table>
<thead>
    <tr>
        <th width="10%">ID</th>
        <th width="30%">Item Name</th>
        <th width="15%">Quantity</th>
        <th width="45%">Description</th>
    </tr>
</thead>
<tbody>';

while ($row = $result->fetch_assoc()) {
    $html .= '<tr>
        <td>' . $row['id'] . '</td>
        <td>' . htmlspecialchars($row['item_name']) . '</td>
        <td>' . $row['quantity'] . '</td>
        <td>' . htmlspecialchars($row['description']) . '</td>
    </tr>';
}

$html .= '</tbody></table>';

$pdf->writeHTML($html, true, false, true, false, '');

// Output
$pdf->Output('inventory_report.pdf', 'D');
exit;
